import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { Printer, FileText, LayoutTemplate, Sparkles, Download, Loader2 } from "lucide-react";

// A4 @ 72dpi = 595x842pt. Preview renders at 96dpi so 1pt = 1.3333px.
// Match the server-side pdf-lib layout exactly (margins, fonts, KPI grid, table cols).
const PT = 1.3333;
const A4_W = 595 * PT; // ~794px
const A4_H = 842 * PT; // ~1123px
const MARGIN = 40 * PT; // ~53px
import { toast } from "sonner";

type Lang = "ar" | "en";
type Template = "classic" | "modern" | "minimal";

const T = {
  ar: {
    title: "تقارير PDF",
    subtitle: "اختر القالب واللغة ثم صدّر التقرير كملف PDF (Ctrl/Cmd+P → حفظ كـ PDF).",
    language: "اللغة",
    template: "القالب",
    download: "تصدير PDF",
    serverDownload: "تنزيل PDF من السيرفر",
    generating: "جاري التوليد…",
    preview: "معاينة",
    templates: { classic: "كلاسيكي", modern: "عصري", minimal: "مبسّط" },
    reportTitle: "تقرير الأداء الشهري",
    company: "HBSpro — إدارة العقارات",
    date: "التاريخ",
    period: "الفترة",
    summary: "ملخص تنفيذي",
    summaryBody:
      "أداء قوي هذا الشهر مع نمو الإيرادات بنسبة 12٪ مقارنة بالشهر السابق، وارتفاع معدل الإشغال إلى 94٪. تم إغلاق 18 صفقة تأجير جديدة وتحصيل 96٪ من مستحقات الإيجار.",
    kpis: [
      { k: "الإيرادات", v: "١٫٢٤٠٫٠٠٠ ر.س" },
      { k: "معدل الإشغال", v: "٩٤٪" },
      { k: "صفقات جديدة", v: "١٨" },
      { k: "التحصيل", v: "٩٦٪" },
    ],
    tableHead: ["#", "العقار", "المستأجر", "المبلغ", "الحالة"],
    rows: [
      ["1", "برج المروج A", "شركة الأفق", "٤٥٫٠٠٠", "مدفوع"],
      ["2", "فيلا الياسمين 12", "أحمد المطيري", "٢٢٫٠٠٠", "مدفوع"],
      ["3", "مكاتب النخيل 3", "مجموعة نوفا", "٦٨٫٠٠٠", "قيد التحصيل"],
      ["4", "شقق الواحة 7B", "سارة القحطاني", "١٨٫٠٠٠", "مدفوع"],
    ],
    footer: "تم إنشاؤه بواسطة HBSpro — سري ومخصص للاستخدام الداخلي.",
  },
  en: {
    title: "PDF Reports",
    subtitle: "Pick a template and language, then export as PDF (Ctrl/Cmd+P → Save as PDF).",
    language: "Language",
    template: "Template",
    download: "Export PDF",
    serverDownload: "Download server PDF",
    generating: "Generating…",
    preview: "Preview",
    templates: { classic: "Classic", modern: "Modern", minimal: "Minimal" },
    reportTitle: "Monthly Performance Report",
    company: "HBSpro — Real Estate Management",
    date: "Date",
    period: "Period",
    summary: "Executive Summary",
    summaryBody:
      "Strong month with revenue up 12% MoM and occupancy at 94%. Closed 18 new leases and collected 96% of rent due.",
    kpis: [
      { k: "Revenue", v: "SAR 1,240,000" },
      { k: "Occupancy", v: "94%" },
      { k: "New Deals", v: "18" },
      { k: "Collections", v: "96%" },
    ],
    tableHead: ["#", "Property", "Tenant", "Amount", "Status"],
    rows: [
      ["1", "Marooj Tower A", "Ufuq Co.", "45,000", "Paid"],
      ["2", "Yasmin Villa 12", "A. Al-Mutairi", "22,000", "Paid"],
      ["3", "Nakheel Offices 3", "Nova Group", "68,000", "Pending"],
      ["4", "Waha Apartments 7B", "S. Al-Qahtani", "18,000", "Paid"],
    ],
    footer: "Generated by HBSpro — Confidential, internal use only.",
  },
} as const;

export const Route = createFileRoute("/_authenticated/dashboard/reports/pdf")({
  component: ReportsPdfPage,
});

function ReportsPdfPage() {
  const [lang, setLang] = useState<Lang>("ar");
  const [template, setTemplate] = useState<Template>("classic");
  const [busy, setBusy] = useState(false);
  const [brand, setBrand] = useState({
    company: "",
    phone: "0555208213",
    email: "hamid@hrhbs.com",
    website: "www.hrhbs.com",
  });
  useEffect(() => {
    (async () => {
      const keys = ["report.company_name", "report.phone", "report.email", "report.website"];
      const results = await Promise.all(
        keys.map((k) => supabase.rpc("get_app_setting", { _key: k })),
      );
      setBrand((b) => ({
        company: (results[0].data as string | null) ?? b.company,
        phone: (results[1].data as string | null) ?? b.phone,
        email: (results[2].data as string | null) ?? b.email,
        website: (results[3].data as string | null) ?? b.website,
      }));
    })();
  }, []);
  const t = T[lang];
  const tt = { ...t, company: brand.company || t.company };
  const today = useMemo(
    () => new Date().toLocaleDateString(lang === "ar" ? "ar-SA" : "en-GB"),
    [lang],
  );

  return (
    <div className="mx-auto max-w-6xl space-y-6 p-6">
      <div className="no-print flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">{t.title}</h1>
          <p className="text-sm text-muted-foreground">{t.subtitle}</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => window.print()} className="gap-2">
            <Printer className="size-4" /> {t.download}
          </Button>
          <Button
            disabled={busy}
            onClick={async () => {
              setBusy(true);
              try {
                const res = await fetch("/api/public/pdf-report", {
                  method: "POST",
                  headers: { "Content-Type": "application/json" },
                  body: JSON.stringify({ lang, template }),
                });
                if (!res.ok) throw new Error(await res.text());
                const blob = await res.blob();
                const url = URL.createObjectURL(blob);
                const a = document.createElement("a");
                a.href = url;
                a.download = `hbspro-report-${template}-${lang}.pdf`;
                document.body.appendChild(a);
                a.click();
                a.remove();
                setTimeout(() => URL.revokeObjectURL(url), 4000);
              } catch (e: any) {
                toast.error(e?.message ?? "PDF generation failed");
              } finally {
                setBusy(false);
              }
            }}
            className="gap-2"
          >
            {busy ? <Loader2 className="size-4 animate-spin" /> : <Download className="size-4" />}
            {busy ? t.generating : t.serverDownload}
          </Button>
        </div>
      </div>

      <div className="no-print grid gap-4 md:grid-cols-2">
        <Card className="p-4">
          <div className="mb-2 text-xs font-semibold uppercase text-muted-foreground">
            {t.language}
          </div>
          <div className="flex gap-2">
            {(["ar", "en"] as Lang[]).map((l) => (
              <button
                key={l}
                onClick={() => setLang(l)}
                className={cn(
                  "flex-1 rounded-md border px-3 py-2 text-sm transition",
                  lang === l
                    ? "border-primary bg-primary text-primary-foreground"
                    : "border-border hover:bg-muted",
                )}
              >
                {l === "ar" ? "العربية" : "English"}
              </button>
            ))}
          </div>
        </Card>
        <Card className="p-4">
          <div className="mb-2 text-xs font-semibold uppercase text-muted-foreground">
            {t.template}
          </div>
          <div className="grid grid-cols-3 gap-2">
            {(["classic", "modern", "minimal"] as Template[]).map((tp) => {
              const Icon =
                tp === "classic" ? FileText : tp === "modern" ? Sparkles : LayoutTemplate;
              return (
                <button
                  key={tp}
                  onClick={() => setTemplate(tp)}
                  className={cn(
                    "flex flex-col items-center gap-1 rounded-md border px-2 py-3 text-xs transition",
                    template === tp
                      ? "border-primary bg-primary/10"
                      : "border-border hover:bg-muted",
                  )}
                >
                  <Icon className="size-4" />
                  {t.templates[tp]}
                </button>
              );
            })}
          </div>
        </Card>
      </div>

      <div className="rounded-xl border border-border/60 bg-muted/30 p-4">
        <div className="no-print mb-3 text-xs font-semibold uppercase text-muted-foreground">
          {t.preview}
        </div>
        <div id="pdf-print-area" dir={lang === "ar" ? "rtl" : "ltr"} className="mx-auto">
          <ReportSheet
            template={template}
            lang={lang}
            t={tt as unknown as (typeof T)[Lang]}
            today={today}
          />
        </div>
      </div>

      <style>{`
        #pdf-print-area { font-family: ${lang === "ar" ? "'Noto Naskh Arabic','Amiri',serif" : "'Inter',system-ui,sans-serif"}; }
        #pdf-print-area .sheet { direction: ${lang === "ar" ? "rtl" : "ltr"}; }
        @media print {
          @page { size: A4; margin: 0; }
          body * { visibility: hidden !important; }
          #pdf-print-area, #pdf-print-area * { visibility: visible !important; }
          #pdf-print-area { position: absolute; inset: 0; margin: 0 !important; padding: 0 !important; background: white !important; color: black !important; }
          #pdf-print-area .sheet { box-shadow: none !important; width: 210mm !important; height: 297mm !important; }
          .no-print { display: none !important; }
        }
      `}</style>
    </div>
  );
}

function ReportSheet({
  template,
  lang,
  t,
  today,
}: {
  template: Template;
  lang: Lang;
  t: (typeof T)[Lang];
  today: string;
}) {
  const period = lang === "ar" ? "نوفمبر ٢٠٢٦" : "November 2026";
  const rtl = lang === "ar";

  // Palette mirrors the server pdf-lib code
  const accent =
    template === "modern"
      ? "rgb(82,56,219)"
      : template === "minimal"
        ? "rgb(51,51,51)"
        : "rgb(26,26,38)";
  const muted = "rgb(115,115,128)";
  const black = "rgb(13,13,26)";

  // Table columns mirror server: [30,160,150,90,90] pt
  const colsPt = [30, 160, 150, 90, 90];
  const totalColW = colsPt.reduce((a, b) => a + b, 0);

  const meta = `${t.date}: ${today}  ·  ${t.period}: ${period}`;
  const isModern = template === "modern";

  return (
    <div
      className="sheet mx-auto bg-white text-neutral-900 shadow-2xl"
      style={{
        width: `${A4_W}px`,
        height: `${A4_H}px`,
        position: "relative",
        overflow: "hidden",
        color: black,
      }}
    >
      {/* Header */}
      {isModern ? (
        <div
          style={{
            position: "absolute",
            top: 0,
            insetInline: 0,
            height: `${130 * PT}px`,
            background: accent,
            color: "white",
            padding: `${25 * PT}px ${MARGIN}px`,
          }}
        >
          <div
            style={{
              fontSize: `${9 * PT}px`,
              opacity: 0.85,
              textTransform: "uppercase",
              letterSpacing: "0.15em",
            }}
          >
            {t.company}
          </div>
          <div style={{ fontSize: `${22 * PT}px`, fontWeight: 700, marginTop: `${8 * PT}px` }}>
            {t.reportTitle}
          </div>
          <div style={{ fontSize: `${9 * PT}px`, opacity: 0.9, marginTop: `${10 * PT}px` }}>
            {meta}
          </div>
        </div>
      ) : (
        <div style={{ position: "absolute", top: MARGIN, insetInline: MARGIN }}>
          <div
            style={{
              fontSize: `${9 * PT}px`,
              color: muted,
              textTransform: "uppercase",
              letterSpacing: "0.15em",
            }}
          >
            {t.company}
          </div>
          <div
            style={{
              fontSize: `${(template === "minimal" ? 22 : 18) * PT}px`,
              fontWeight: template === "minimal" ? 300 : 700,
              marginTop: `${8 * PT}px`,
              color: black,
            }}
          >
            {t.reportTitle}
          </div>
          <div style={{ fontSize: `${9 * PT}px`, color: muted, marginTop: `${8 * PT}px` }}>
            {meta}
          </div>
          <div
            style={{
              marginTop: `${10 * PT}px`,
              borderTop: template === "classic" ? `1.5px solid ${black}` : `0.5px solid ${muted}`,
            }}
          />
        </div>
      )}

      {/* Body */}
      <div
        style={{
          position: "absolute",
          top: isModern ? `${160 * PT}px` : `${(MARGIN / PT + 90) * PT}px`,
          insetInline: MARGIN,
          bottom: MARGIN,
        }}
      >
        {/* Summary */}
        <div style={{ marginBottom: `${18 * PT}px` }}>
          <div
            style={{
              fontSize: `${11 * PT}px`,
              fontWeight: 700,
              color: accent,
              marginBottom: `${6 * PT}px`,
            }}
          >
            {t.summary}
          </div>
          <p style={{ fontSize: `${10 * PT}px`, lineHeight: 1.5, color: black, margin: 0 }}>
            {t.summaryBody}
          </p>
        </div>

        {/* KPI grid — 4 equal cards, 12pt gap */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(4, 1fr)",
            gap: `${12 * PT}px`,
            marginBottom: `${20 * PT}px`,
          }}
        >
          {t.kpis.map((k) => (
            <div
              key={k.k}
              style={{
                height: `${50 * PT}px`,
                border: `0.5px solid ${muted}`,
                background: isModern ? "rgb(245,245,255)" : "white",
                padding: `${8 * PT}px`,
              }}
            >
              <div
                style={{
                  fontSize: `${8 * PT}px`,
                  color: muted,
                  textTransform: "uppercase",
                  letterSpacing: "0.1em",
                }}
              >
                {k.k}
              </div>
              <div
                style={{
                  fontSize: `${13 * PT}px`,
                  fontWeight: 700,
                  marginTop: `${6 * PT}px`,
                  color: black,
                }}
              >
                {k.v}
              </div>
            </div>
          ))}
        </div>

        {/* Table — mirror server column widths */}
        <table
          style={{
            width: `${totalColW * PT}px`,
            margin: "0 auto",
            borderCollapse: "collapse",
            tableLayout: "fixed",
            direction: rtl ? "rtl" : "ltr",
          }}
        >
          <colgroup>
            {colsPt.map((c, i) => (
              <col key={i} style={{ width: `${c * PT}px` }} />
            ))}
          </colgroup>
          <thead>
            <tr
              style={{
                height: `${20 * PT}px`,
                background:
                  template === "modern"
                    ? "rgb(237,237,255)"
                    : template === "classic"
                      ? black
                      : "white",
                color: template === "classic" ? "white" : template === "modern" ? accent : muted,
              }}
            >
              {t.tableHead.map((h) => (
                <th
                  key={h}
                  style={{
                    fontSize: `${9 * PT}px`,
                    fontWeight: 700,
                    padding: `0 ${6 * PT}px`,
                    textAlign: rtl ? "right" : "left",
                    textTransform: "uppercase",
                    letterSpacing: "0.05em",
                  }}
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {t.rows.map((r, i) => (
              <tr
                key={i}
                style={{
                  height: `${20 * PT}px`,
                  background: i % 2 && template === "classic" ? "rgb(245,245,245)" : "transparent",
                  borderBottom: `0.3px solid ${muted}`,
                }}
              >
                {r.map((c, j) => (
                  <td
                    key={j}
                    style={{
                      fontSize: `${9 * PT}px`,
                      padding: `0 ${6 * PT}px`,
                      color: black,
                      textAlign: rtl ? "right" : "left",
                    }}
                  >
                    {c}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Footer */}
      <div
        style={{
          position: "absolute",
          insetInline: MARGIN,
          bottom: `${20 * PT}px`,
          fontSize: `${8 * PT}px`,
          color: muted,
        }}
      >
        <div
          style={{
            borderTop: `0.5px solid ${muted}`,
            paddingTop: `${6 * PT}px`,
            marginBottom: `${6 * PT}px`,
            fontWeight: 700,
            color: accent,
            direction: rtl ? "rtl" : "ltr",
          }}
        >
          {rtl
            ? "رقم الجوال: 0555208213  ·  hamid@hrhbs.com  ·  www.hrhbs.com"
            : "Mobile: 0555208213  ·  hamid@hrhbs.com  ·  www.hrhbs.com"}
        </div>
        {t.footer}
      </div>
    </div>
  );
}
