import { createFileRoute } from "@tanstack/react-router";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
// @ts-ignore
import arabicReshaper from "arabic-reshaper";
// @ts-ignore
import bidiFactory from "bidi-js";

const bidi = bidiFactory();

const SIGNATURE_DEFAULTS = {
  company: "HBSpro — إدارة العقارات",
  phone: "0555208213",
  email: "hamid@hrhbs.com",
  website: "www.hrhbs.com",
};

type SigPos = "top" | "bottom";
type SigAlign = "start" | "center" | "end";
type SigLayout = { position: SigPos; offset: number; align: SigAlign };
const SIG_LAYOUT_DEFAULTS: Record<Template, SigLayout> = {
  classic: { position: "bottom", offset: 26, align: "start" },
  modern: { position: "bottom", offset: 26, align: "start" },
  minimal: { position: "bottom", offset: 26, align: "center" },
};

async function loadBrandingSettings() {
  try {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data } = await supabaseAdmin
      .from("app_settings")
      .select("key,value")
      .in("key", [
        "report.company_name",
        "report.phone",
        "report.email",
        "report.website",
        "report.sig_layout",
        "report.contact_in_header",
        "report.company_id",
        "report.use_company_settings",
      ]);
    const m = new Map((data ?? []).map((r: any) => [r.key, r.value as string]));
    let layout = SIG_LAYOUT_DEFAULTS;
    try {
      const raw = m.get("report.sig_layout");
      if (raw) layout = { ...SIG_LAYOUT_DEFAULTS, ...JSON.parse(raw) };
    } catch {}
    let company = m.get("report.company_name") || SIGNATURE_DEFAULTS.company;
    let phone = m.get("report.phone") || SIGNATURE_DEFAULTS.phone;
    let email = m.get("report.email") || SIGNATURE_DEFAULTS.email;
    const website = m.get("report.website") || SIGNATURE_DEFAULTS.website;

    // Data source: linked Company Settings row (public.companies) overrides
    // the free-text signature fields when enabled.
    const useCompany = (m.get("report.use_company_settings") ?? "false") === "true";
    const linkedCompanyId = m.get("report.company_id") || null;
    let sourceCompanyId: string | null = null;
    if (useCompany && linkedCompanyId) {
      const { data: co } = await supabaseAdmin
        .from("companies")
        .select("id,name,phone,email")
        .eq("id", linkedCompanyId)
        .is("deleted_at", null)
        .maybeSingle();
      if (co) {
        sourceCompanyId = co.id;
        if (co.name) company = co.name;
        if (co.phone) phone = co.phone;
        if (co.email) email = co.email;
      }
    }

    return {
      company,
      phone,
      email,
      website,
      layout,
      contactInHeader: (m.get("report.contact_in_header") ?? "false") === "true",
      sourceCompanyId,
    };
  } catch {
    return {
      ...SIGNATURE_DEFAULTS,
      layout: SIG_LAYOUT_DEFAULTS,
      contactInHeader: false,
      sourceCompanyId: null,
    };
  }
}

type Lang = "ar" | "en";
type Template = "classic" | "modern" | "minimal";

const AR = {
  reportTitle: "تقرير الأداء الشهري",
  company: "HBSpro — إدارة العقارات",
  date: "التاريخ",
  period: "الفترة",
  summary: "ملخص تنفيذي",
  summaryBody:
    "أداء قوي هذا الشهر مع نمو الإيرادات بنسبة 12٪ مقارنة بالشهر السابق، وارتفاع معدل الإشغال إلى 94٪. تم إغلاق 18 صفقة تأجير جديدة وتحصيل 96٪ من مستحقات الإيجار.",
  kpis: [
    ["الإيرادات", "1,240,000 SAR"],
    ["معدل الإشغال", "94%"],
    ["صفقات جديدة", "18"],
    ["التحصيل", "96%"],
  ],
  head: ["#", "العقار", "المستأجر", "المبلغ", "الحالة"],
  rows: [
    ["1", "برج المروج A", "شركة الأفق", "45,000", "مدفوع"],
    ["2", "فيلا الياسمين 12", "أحمد المطيري", "22,000", "مدفوع"],
    ["3", "مكاتب النخيل 3", "مجموعة نوفا", "68,000", "قيد التحصيل"],
    ["4", "شقق الواحة 7B", "سارة القحطاني", "18,000", "مدفوع"],
  ],
  footer: "تم إنشاؤه بواسطة HBSpro — سري ومخصص للاستخدام الداخلي.",
  period_v: "نوفمبر 2026",
};

const EN = {
  reportTitle: "Monthly Performance Report",
  company: "HBSpro — Real Estate Management",
  date: "Date",
  period: "Period",
  summary: "Executive Summary",
  summaryBody:
    "Strong month with revenue up 12% MoM and occupancy at 94%. Closed 18 new leases and collected 96% of rent due.",
  kpis: [
    ["Revenue", "SAR 1,240,000"],
    ["Occupancy", "94%"],
    ["New Deals", "18"],
    ["Collections", "96%"],
  ],
  head: ["#", "Property", "Tenant", "Amount", "Status"],
  rows: [
    ["1", "Marooj Tower A", "Ufuq Co.", "45,000", "Paid"],
    ["2", "Yasmin Villa 12", "A. Al-Mutairi", "22,000", "Paid"],
    ["3", "Nakheel Offices 3", "Nova Group", "68,000", "Pending"],
    ["4", "Waha Apartments 7B", "S. Al-Qahtani", "18,000", "Paid"],
  ],
  footer: "Generated by HBSpro — Confidential, internal use only.",
  period_v: "November 2026",
};

// Shape Arabic text (contextual joining + bidi reorder) so pdf-lib renders it correctly.
function shape(text: string, lang: Lang): string {
  if (lang !== "ar") return text;
  const reshaped = arabicReshaper.convertArabic(text);
  const embeddingLevels = bidi.getEmbeddingLevels(reshaped, "rtl");
  return bidi.getReorderedString(reshaped, embeddingLevels);
}

let _fontCache: { regular: Uint8Array; bold: Uint8Array } | null = null;
async function loadArabicFonts(): Promise<{ regular: Uint8Array; bold: Uint8Array }> {
  if (_fontCache) return _fontCache;
  // jsDelivr mirror of googlefonts/noto-fonts — reliable from edge workers.
  const base = "https://cdn.jsdelivr.net/gh/googlefonts/noto-fonts@main/hinted/ttf/NotoNaskhArabic";
  const fetchFont = async (url: string) => {
    const r = await fetch(url);
    if (!r.ok) throw new Error(`Font fetch failed (${r.status}) for ${url}`);
    return r.arrayBuffer();
  };
  const [reg, bold] = await Promise.all([
    fetchFont(`${base}/NotoNaskhArabic-Regular.ttf`),
    fetchFont(`${base}/NotoNaskhArabic-Bold.ttf`),
  ]);
  _fontCache = { regular: new Uint8Array(reg), bold: new Uint8Array(bold) };
  return _fontCache;
}

export const Route = createFileRoute("/api/public/pdf-report")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const { lang = "en", template = "classic" } = (await request.json().catch(() => ({}))) as {
          lang?: Lang;
          template?: Template;
        };

        const t = lang === "ar" ? AR : EN;
        const brand = await loadBrandingSettings();
        // Company name is admin-configurable and overrides the built-in.
        t.company = brand.company;
        const doc = await PDFDocument.create();
        doc.registerFontkit(fontkit);

        let regular, bold;
        if (lang === "ar") {
          const fonts = await loadArabicFonts();
          // subset:false embeds the FULL font so every Arabic glyph renders
          // identically on any device/PDF viewer (no fallback substitution).
          regular = await doc.embedFont(fonts.regular, { subset: false });
          bold = await doc.embedFont(fonts.bold, { subset: false });
          doc.setLanguage("ar");
        } else {
          regular = await doc.embedFont(StandardFonts.Helvetica);
          bold = await doc.embedFont(StandardFonts.HelveticaBold);
          doc.setLanguage("en");
        }

        const page = doc.addPage([595, 842]); // A4
        const { width, height } = page.getSize();
        const margin = 40;
        const rtl = lang === "ar";

        // Palette per template
        const accent =
          template === "modern"
            ? rgb(0.32, 0.22, 0.86)
            : template === "minimal"
              ? rgb(0.2, 0.2, 0.2)
              : rgb(0.1, 0.1, 0.15);
        const muted = rgb(0.45, 0.45, 0.5);
        const black = rgb(0.05, 0.05, 0.1);

        const draw = (
          text: string,
          x: number,
          y: number,
          size = 10,
          font = regular,
          color = black,
          align: "left" | "right" = rtl ? "right" : "left",
        ) => {
          const s = shape(text, lang);
          const w = font.widthOfTextAtSize(s, size);
          const drawX = align === "right" ? x - w : x;
          page.drawText(s, { x: drawX, y, size, font, color });
        };

        const startX = rtl ? width - margin : margin;
        let y = height - margin;

        // Header
        if (template === "modern") {
          page.drawRectangle({
            x: 0,
            y: height - 130,
            width,
            height: 130,
            color: accent,
          });
          draw(t.company, startX, height - 55, 9, regular, rgb(1, 1, 1));
          draw(t.reportTitle, startX, height - 85, 22, bold, rgb(1, 1, 1));
          draw(
            `${t.date}: ${new Date().toLocaleDateString(lang === "ar" ? "ar-SA" : "en-GB")}  ·  ${t.period}: ${t.period_v}`,
            startX,
            height - 110,
            9,
            regular,
            rgb(1, 1, 1),
          );
          y = height - 160;
        } else {
          draw(t.company, startX, y - 10, 9, regular, muted);
          draw(t.reportTitle, startX, y - 35, template === "minimal" ? 22 : 18, bold, black);
          draw(
            `${t.date}: ${new Date().toLocaleDateString(lang === "ar" ? "ar-SA" : "en-GB")}  ·  ${t.period}: ${t.period_v}`,
            startX,
            y - 55,
            9,
            regular,
            muted,
          );
          page.drawLine({
            start: { x: margin, y: y - 65 },
            end: { x: width - margin, y: y - 65 },
            thickness: template === "classic" ? 1.5 : 0.5,
            color: template === "classic" ? black : muted,
          });
          y = y - 90;
        }

        // Summary
        draw(t.summary, startX, y, 11, bold, accent);
        y -= 18;
        // Word-wrap body
        const bodyShaped = shape(t.summaryBody, lang);
        const maxW = width - margin * 2;
        const words = bodyShaped.split(" ");
        let line = "";
        for (const w of words) {
          const test = line ? line + " " + w : w;
          if (regular.widthOfTextAtSize(test, 10) > maxW) {
            const lineW = regular.widthOfTextAtSize(line, 10);
            page.drawText(line, {
              x: rtl ? startX - lineW : margin,
              y,
              size: 10,
              font: regular,
              color: black,
            });
            y -= 14;
            line = w;
          } else line = test;
        }
        if (line) {
          const lineW = regular.widthOfTextAtSize(line, 10);
          page.drawText(line, {
            x: rtl ? startX - lineW : margin,
            y,
            size: 10,
            font: regular,
            color: black,
          });
          y -= 20;
        }

        // KPIs
        y -= 10;
        const cardW = (width - margin * 2 - 12 * 3) / 4;
        const cardH = 50;
        for (let i = 0; i < t.kpis.length; i++) {
          const cx = margin + i * (cardW + 12);
          page.drawRectangle({
            x: cx,
            y: y - cardH,
            width: cardW,
            height: cardH,
            borderColor: muted,
            borderWidth: 0.5,
            color: template === "modern" ? rgb(0.96, 0.96, 1) : rgb(1, 1, 1),
          });
          const [k, v] = t.kpis[i];
          const ks = shape(k, lang);
          const vs = shape(v, lang);
          page.drawText(ks, {
            x: cx + 8,
            y: y - 16,
            size: 8,
            font: regular,
            color: muted,
          });
          page.drawText(vs, {
            x: cx + 8,
            y: y - 36,
            size: 13,
            font: bold,
            color: black,
          });
        }
        y -= cardH + 20;

        // Table
        const cols = [30, 160, 150, 90, 90];
        const totalW = cols.reduce((a, b) => a + b, 0);
        const tableX = margin + (width - margin * 2 - totalW) / 2;
        // Header row
        page.drawRectangle({
          x: tableX,
          y: y - 20,
          width: totalW,
          height: 20,
          color:
            template === "modern"
              ? rgb(0.93, 0.93, 1)
              : template === "classic"
                ? black
                : rgb(1, 1, 1),
        });
        const headColor =
          template === "classic" ? rgb(1, 1, 1) : template === "modern" ? accent : muted;
        let hx = tableX;
        for (let i = 0; i < t.head.length; i++) {
          const idx = rtl ? t.head.length - 1 - i : i;
          const s = shape(t.head[idx], lang);
          page.drawText(s, {
            x: hx + 6,
            y: y - 14,
            size: 9,
            font: bold,
            color: headColor,
          });
          hx += cols[i];
        }
        y -= 20;
        for (let r = 0; r < t.rows.length; r++) {
          if (r % 2 && template === "classic") {
            page.drawRectangle({
              x: tableX,
              y: y - 20,
              width: totalW,
              height: 20,
              color: rgb(0.96, 0.96, 0.96),
            });
          }
          let cx = tableX;
          for (let i = 0; i < cols.length; i++) {
            const idx = rtl ? cols.length - 1 - i : i;
            const s = shape(t.rows[r][idx], lang);
            page.drawText(s, {
              x: cx + 6,
              y: y - 14,
              size: 9,
              font: regular,
              color: black,
            });
            cx += cols[i];
          }
          page.drawLine({
            start: { x: tableX, y: y - 20 },
            end: { x: tableX + totalW, y: y - 20 },
            thickness: 0.3,
            color: muted,
          });
          y -= 20;
        }

        // Signature block — configurable position/align/offset per template, RTL-aware.
        const sig = brand.layout[template];
        const sigY =
          sig.position === "bottom"
            ? margin + Math.max(0, sig.offset)
            : height - margin - Math.max(0, sig.offset);
        const sigLine =
          lang === "ar"
            ? `رقم الجوال: ${brand.phone}  ·  ${brand.email}  ·  ${brand.website}`
            : `Mobile: ${brand.phone}  ·  ${brand.email}  ·  ${brand.website}`;
        const sigShaped = shape(sigLine, lang);
        const sigW = bold.widthOfTextAtSize(sigShaped, 8);
        // Map logical start/end to physical left/right based on RTL.
        const physicalRight = sig.align === "center" ? undefined : sig.align === "end" ? !rtl : rtl;
        const sigX =
          sig.align === "center"
            ? (width - sigW) / 2
            : physicalRight
              ? width - margin - sigW
              : margin;
        page.drawLine({
          start: { x: margin, y: sigY + 14 },
          end: { x: width - margin, y: sigY + 14 },
          thickness: 0.5,
          color: muted,
        });
        page.drawText(sigShaped, { x: sigX, y: sigY, size: 8, font: bold, color: accent });
        // Keep the report footer at the very bottom.
        draw(t.footer, startX, margin, 8, regular, muted);

        // Optional: repeat contact strip in the header of every page.
        if (brand.contactInHeader) {
          const headerLine =
            lang === "ar"
              ? `رقم الجوال: ${brand.phone}  ·  ${brand.email}  ·  ${brand.website}`
              : `Mobile: ${brand.phone}  ·  ${brand.email}  ·  ${brand.website}`;
          const headerShaped = shape(headerLine, lang);
          const hSize = 8;
          const hW = regular.widthOfTextAtSize(headerShaped, hSize);
          for (const p of doc.getPages()) {
            const { width: pw, height: ph } = p.getSize();
            const hY = ph - 18;
            const hX = rtl ? pw - margin - hW : margin;
            p.drawText(headerShaped, { x: hX, y: hY, size: hSize, font: regular, color: muted });
            p.drawLine({
              start: { x: margin, y: hY - 4 },
              end: { x: pw - margin, y: hY - 4 },
              thickness: 0.3,
              color: muted,
            });
          }
        }

        const bytes = await doc.save();
        const filename = `hbspro-report-${template}-${lang}.pdf`;
        return new Response(bytes as unknown as BodyInit, {
          status: 200,
          headers: {
            "Content-Type": "application/pdf",
            "Content-Disposition": `attachment; filename="${filename}"`,
            "Cache-Control": "no-store",
          },
        });
      },
    },
  },
});
