
CREATE INDEX IF NOT EXISTS idx_app_settings_updated_by ON public.app_settings(updated_by);
CREATE INDEX IF NOT EXISTS idx_profiles_manager_id ON public.profiles(manager_id);
CREATE INDEX IF NOT EXISTS idx_organizations_created_by ON public.organizations(created_by);
CREATE INDEX IF NOT EXISTS idx_properties_created_by ON public.properties(created_by);
CREATE INDEX IF NOT EXISTS idx_contacts_created_by ON public.contacts(created_by);
CREATE INDEX IF NOT EXISTS idx_leads_assigned_to ON public.leads(assigned_to);
CREATE INDEX IF NOT EXISTS idx_leads_created_by ON public.leads(created_by);
CREATE INDEX IF NOT EXISTS idx_leads_property_id ON public.leads(property_id);
CREATE INDEX IF NOT EXISTS idx_deals_created_by ON public.deals(created_by);
CREATE INDEX IF NOT EXISTS idx_deals_primary_contact_id ON public.deals(primary_contact_id);
CREATE INDEX IF NOT EXISTS idx_commissions_agent_id ON public.commissions(agent_id);
CREATE INDEX IF NOT EXISTS idx_commissions_created_by ON public.commissions(created_by);
CREATE INDEX IF NOT EXISTS idx_tasks_contact_id ON public.tasks(contact_id);
CREATE INDEX IF NOT EXISTS idx_tasks_created_by ON public.tasks(created_by);
CREATE INDEX IF NOT EXISTS idx_tasks_deal_id ON public.tasks(deal_id);
CREATE INDEX IF NOT EXISTS idx_tasks_lead_id ON public.tasks(lead_id);
CREATE INDEX IF NOT EXISTS idx_tasks_property_id ON public.tasks(property_id);
CREATE INDEX IF NOT EXISTS idx_invoices_contact_id ON public.invoices(contact_id);
CREATE INDEX IF NOT EXISTS idx_invoices_created_by ON public.invoices(created_by);
CREATE INDEX IF NOT EXISTS idx_invoices_deal_id ON public.invoices(deal_id);
CREATE INDEX IF NOT EXISTS idx_invoices_property_id ON public.invoices(property_id);
CREATE INDEX IF NOT EXISTS idx_expenses_created_by ON public.expenses(created_by);
CREATE INDEX IF NOT EXISTS idx_expenses_property_id ON public.expenses(property_id);
CREATE INDEX IF NOT EXISTS idx_technicians_created_by ON public.technicians(created_by);
CREATE INDEX IF NOT EXISTS idx_mt_created_by ON public.maintenance_tickets(created_by);
CREATE INDEX IF NOT EXISTS idx_mt_property_id ON public.maintenance_tickets(property_id);
CREATE INDEX IF NOT EXISTS idx_mt_reported_by ON public.maintenance_tickets(reported_by_contact_id);
CREATE INDEX IF NOT EXISTS idx_mt_technician_id ON public.maintenance_tickets(technician_id);
CREATE INDEX IF NOT EXISTS idx_documents_contact_id ON public.documents(contact_id);
CREATE INDEX IF NOT EXISTS idx_documents_created_by ON public.documents(created_by);
CREATE INDEX IF NOT EXISTS idx_documents_current_version_id ON public.documents(current_version_id);
CREATE INDEX IF NOT EXISTS idx_documents_deal_id ON public.documents(deal_id);
CREATE INDEX IF NOT EXISTS idx_documents_property_id ON public.documents(property_id);
CREATE INDEX IF NOT EXISTS idx_docver_org_id ON public.document_versions(org_id);
CREATE INDEX IF NOT EXISTS idx_docver_uploaded_by ON public.document_versions(uploaded_by);
CREATE INDEX IF NOT EXISTS idx_banks_country_id ON public.banks(country_id);
CREATE INDEX IF NOT EXISTS idx_companies_city_id ON public.companies(city_id);
CREATE INDEX IF NOT EXISTS idx_companies_country_id ON public.companies(country_id);
CREATE INDEX IF NOT EXISTS idx_branches_city_id ON public.branches(city_id);
CREATE INDEX IF NOT EXISTS idx_buildings_branch_id ON public.buildings(branch_id);
CREATE INDEX IF NOT EXISTS idx_floors_org_id ON public.floors(org_id);
CREATE INDEX IF NOT EXISTS idx_units_floor_id ON public.units(floor_id);
CREATE INDEX IF NOT EXISTS idx_owners_bank_id ON public.owners(bank_id);
CREATE INDEX IF NOT EXISTS idx_contracts_owner_id ON public.contracts(owner_id);
CREATE INDEX IF NOT EXISTS idx_payments_bank_id ON public.payments(bank_id);
CREATE INDEX IF NOT EXISTS idx_payments_method_id ON public.payments(method_id);
CREATE INDEX IF NOT EXISTS idx_payments_tenant_id ON public.payments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_employees_branch_id ON public.employees(branch_id);
CREATE INDEX IF NOT EXISTS idx_visitors_building_id ON public.visitors(building_id);
CREATE INDEX IF NOT EXISTS idx_visitors_unit_id ON public.visitors(unit_id);
CREATE INDEX IF NOT EXISTS idx_notifications_org_id ON public.notifications(org_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_package_id ON public.subscriptions(package_id);
CREATE INDEX IF NOT EXISTS idx_sms_org_id ON public.sms_providers(org_id);
CREATE INDEX IF NOT EXISTS idx_email_org_id ON public.email_providers(org_id);
CREATE INDEX IF NOT EXISTS idx_backups_org_id ON public.backups(org_id);

-- Composite hot-path indexes
CREATE INDEX IF NOT EXISTS idx_invoices_org_status_due   ON public.invoices(org_id, status, due_date DESC);
CREATE INDEX IF NOT EXISTS idx_expenses_org_spent_at     ON public.expenses(org_id, spent_at DESC);
CREATE INDEX IF NOT EXISTS idx_deals_org_status          ON public.deals(org_id, status);
CREATE INDEX IF NOT EXISTS idx_leads_org_stage           ON public.leads(org_id, stage);
CREATE INDEX IF NOT EXISTS idx_tasks_org_status_due      ON public.tasks(org_id, status, due_at);
CREATE INDEX IF NOT EXISTS idx_contracts_org_status_end  ON public.contracts(org_id, status, end_date);
CREATE INDEX IF NOT EXISTS idx_payments_org_paid_at      ON public.payments(org_id, paid_at DESC);
CREATE INDEX IF NOT EXISTS idx_mt_org_status_priority    ON public.maintenance_tickets(org_id, status, priority);
CREATE INDEX IF NOT EXISTS idx_units_building_status     ON public.units(building_id, status);

ANALYZE;
